"""Initial migration

Revision ID: 9045e68cf4ee
Revises: 
Create Date: 2025-02-01 18:02:29.903188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9045e68cf4ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create tables first
    op.create_table('documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('document_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('text_chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('start_index', sa.Integer(), nullable=True),
        sa.Column('end_index', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('suggestions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('initial_scores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text_chunk_id', sa.Integer(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('final_scores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text_chunk_id', sa.Integer(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Add foreign key constraints
    op.create_foreign_key('fk_document_history_document', 'document_history', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_text_chunks_document', 'text_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_suggestions_document', 'suggestions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_initial_scores_text_chunk', 'initial_scores', 'text_chunks', ['text_chunk_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_final_scores_text_chunk', 'final_scores', 'text_chunks', ['text_chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first
    op.drop_constraint('fk_final_scores_text_chunk', 'final_scores', type_='foreignkey')
    op.drop_constraint('fk_initial_scores_text_chunk', 'initial_scores', type_='foreignkey')
    op.drop_constraint('fk_suggestions_document', 'suggestions', type_='foreignkey')
    op.drop_constraint('fk_text_chunks_document', 'text_chunks', type_='foreignkey')
    op.drop_constraint('fk_document_history_document', 'document_history', type_='foreignkey')

    # Drop tables
    op.drop_table('final_scores')
    op.drop_table('initial_scores')
    op.drop_table('suggestions')
    op.drop_table('text_chunks')
    op.drop_table('document_history')
    op.drop_table('documents')
    # ### end Alembic commands ###
